"""create users table

Revision ID: 87c915f6e779
Revises: 
Create Date: 2026-05-29 14:29:42.288394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c915f6e779'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', sa.Uuid(), server_default=sa.text(
                        'gen_random_uuid()'), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.Column('created_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('updated_at', sa.DateTime(),
                              server_default=sa.text('now()'), nullable=False),
                    sa.Column('first_name', sa.String(
                        length=60), nullable=False),
                    sa.Column('last_name', sa.String(
                        length=60), nullable=False),
                    sa.Column('username', sa.String(
                        length=120), nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.UniqueConstraint('email'),
                    sa.Column('hashed_password', sa.String(
                        length=255), nullable=False),
                    sa.Column('is_admin', sa.Boolean(),
                              server_default=sa.text('false'), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=True)
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
